name: run-fusesoc-targets
on: [push]

jobs:
  build-openlane-sky130:
    runs-on: ubuntu-latest
    env:
      REPO : verilog-dsp
      VLNV : verilog-dsp
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: verilog-dsp
      - run: echo "EDALIZE_LAUNCHER=el_docker" >> $GITHUB_ENV
      - run: pip3 install fusesoc
      - run: fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
      - run: fusesoc run --target=sky130_cic_decimator $VLNV

  lint-verilator-cic-decimator:
    runs-on: ubuntu-latest
    env:
      REPO : verilog-dsp
      VLNV : verilog-dsp
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: verilog-dsp
      - run: sudo apt install verilator
      - run: pip3 install fusesoc
      - run: fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
      - run: fusesoc run --target=lint_cic_decimator $VLNV
